### PR TITLE
Change more broken links in resources page

### PR DESCRIPTION
**Pull request by olivercoad**
Fix more elmish links in https://fable.io/resources.html

Not sure why the \[elmish\] reference at the bottom of the markdown wasn't working when the other references are.

### CODE REVIEW

**Comment by olivercoad** [comment]
Ah that makes sense. Should I push another commit to fix those too in this PR?

**Comment by MangelMaxime** [comment]
Yes, please can you update this PR to fix those links and the elmish link using the correct syntax ?

**Comment by MangelMaxime** [comment]
Thank you

**Comment by olivercoad** [comment]
Okay, I haven't checked every single link but that's all the obvious ones

**Comment by olivercoad** [comment]
That was quick! Just noticed you already merged it. I also pushed [another commit](https://github.com/olivercoad/fable-compiler.github.io/commit/34c2f84e68ca0d0242d92f5c18b4be5fa80ca0b6) to change links to https while we're at it.

**Pull request merged**
