### PR TITLE
Revamp the website to use Nacara for everything

### LINKED ISSUE #86: Considering better documentation tooling
This is going to be a long post, but I think that it should be worth reading.

Recently, I have started learning F# and have noticed that some libraries (including this one) have poor documentation. This includes the outdated content, missing documentation and terrible styling. I don't want to sound negative, but this can be improved a lot.

My background is mainly PHP and JS, so examples of good documentation would be:

- https://laravel.com/docs/8.x
- https://vuejs.org/v2/guide/#What-is-Vue-js
- https://reactjs.org/docs/getting-started.html

Something similar to F#/Fable scenario:

- https://rescript-lang.org/docs/manual/latest/introduction
- https://guide.elm-lang.org/

Then, I have read the documentation of these language and they have something special:

- Elixir https://hexdocs.pm/elixir/Kernel.html
- Go https://golang.org/pkg/

**They use valid code to generate documentation, api documentation and valid examples.**

This got me thinking that I read somewhere while learning F# that for comments you can use XML and something something it can be parsed (way above my head). Then I have stumbled upon a tweet from Don Syme that he has recently pushed a commit to a tool called: 

https://fsprojects.github.io/FSharp.Formatting/

This is the first line on that page:

> F# Formatting: Documentation Tools for F# Code

Upon reading about it these are my opinions:

- This should be used by every F# library
- The default styling should be improved
- This tool should have better documentation :)
- F# Formatting is a terrible name for something like this :) How can you say to someone: "Use F# formatting to generate API documentation for you library."
- The great thing about this library is that inside it you write valid F# code which you can execute and test. This is far better than any PHP/JS documentation. I think that having this means that writing documentation is now fun.
- Option to include markdown files into documentation is great for text heavy pages where there is not a lot of code
- Having the package generate API documentation is a huge time saver and promotes writing good comments.

In conclusion,

let's not reinvent the wheel. There is a package which exists and works made specifically for generating F# documentation. We should use it for everything F# related.

The majority of pages currently on Fable.io website can be moved to that package. I don't know the amount of comments that there are in the code of Fable itself, but I assume that it can fetch the namespaces and functions. I'm going to try to use F# formatting with the main fable repository to see what I get and then try to moved content from this website to that documentation.

I repeat, I don't want to be negative or say bad things about months of work that went into this website (so I have heard), but this can be improved further.

My opinions here are true for other package which I have used so far (Feliz, Fable.React). What is the deal with double scrollbars everywhere :)

### PR DESCRIPTION
**Pull request by MangelMaxime**
⚠️  **Important:** You cannot yet build the Website using Nacara because the new version of Nacara is not yet released ⚠️ 

Fix #86 

I am creating this PR in order to keep track of my progress and list all the changes made.

- Use Nacara for everything
    - [X] Home page
    - [X] Documentation
    - [X] Community section
    - [x] Blog
- Include Fable Awesome directly into Fable website @kunjee17 is ok with that https://github.com/kunjee17/awesome-fable/issues/91
    - [X] Have a placeholder ready
    - [x] Adapt Fable awesome content to work with Nacara as Fable awesome using Github specific features like emojis etc.
    - [ ] Set up the CI to check the links
- [x] Remove custom site generation
- [x] Setup the build system via `npm scripts`

# Home page re-design

The home page of Fable has been rewritten from scratch to use Bulma features as much as possible making it easier to have a consistent display.

The exception being the **selling points** which use CSS grid in order to make sure the box all have the same height which is not possible with flexbox.

Features / main changes:

- Load twitter timeline in background and only show it when ready.

https://user-images.githubusercontent.com/4760796/124019333-36818f80-d9e9-11eb-85fe-72926ea8bd0e.mp4

- Handle the case where twitter timeline loading is blocked by an ad blocker

image

- On touch screen the twitter timeline is hidden, it would be best to not load at all but for now that will be good enough. 

image

- Responsive

https://user-images.githubusercontent.com/4760796/124020062-1acab900-d9ea-11eb-81f8-1b5ec8cb2201.mp4

- Uncluttered design

image

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Here is a preview of the blog section:

I tried several different layouts for the blog but didn't find anything that I liked or was able to make in CSS so for now I propose to keep it simple.

**Blog index page**

https://user-images.githubusercontent.com/4760796/124180978-364ec600-dab5-11eb-9d2e-c4e5701839d0.mp4

**Blog post**

https://user-images.githubusercontent.com/4760796/124181005-41a1f180-dab5-11eb-9726-6bc35d991241.mp4

**Comment by MangelMaxime** [comment]
I think I now have more or less all the layouts figure out.

The blog page got a few additions:

image

I am now focusing on improving contribution experience because I used a lot of standard HTML thinking it would be ok. But after porting a lot of blog post I found that is was a bit tedious and error prone.

Thanks to Nacara ability to add custom layout I am pretty happy where things are going. Adding, a blog post should in the end be as simple as creating a Markdown file and filling the required attributes:

```md
---
title: Introducing 0.7
layout: blogPage
author: Alfonso García-Caro
date: 2016-11-22
author_link: https://twitter.com/alfonsogcnunez
author_image: https://github.com/alfonsogarciacaro.png
description: |
  I've been recently playing with Feliz.Engine and wanted to check how easy was to adapt it to an alternative Virtual-DOM implementation, like Snabbdom.
  This started just as an experiment but I've been pleasantly surprised by how simple yet powerful Snabbdom is, and more importantly how well it fits with the Elmish architecture
---

The blog content goes here
```

[Example](https://github.com/fable-compiler/fable-compiler.github.io/pull/98/files#diff-2140871fea593369ed1a658e212af1450a4f748aa141587927b40d540c6014fbR1-R12)

I am now working on making the blog page index auto generate from the blog files.

**Comment by mabasic** [comment]
I have just seen this issue. Very nice work indeed. It is all coming together now.

I have an idea for the twitter feed. I'm not a huge fan of it and the widget looks out of place. Maybe we could write JS (Fable/F#) to grab related tweets and display them natively so that it matches the website design?

**Comment by MangelMaxime** [comment]
> I have just seen this issue. Very nice work indeed. It is all coming together now.

Yes, it is close to be ready for testing and review. I am almost done rewriting Nacara making it cleaner to add layouts etc.

> I have an idea for the twitter feed. I'm not a huge fan of it and the widget looks out of place. Maybe we could write JS (Fable/F#) to grab related tweets and display them natively so that it matches the website design?

One "problem" with using Twitter API is that we will could encounter rate limit and this can add complexity. So depending on the limitation and if someone is willing to give it a try perhaps it will happen.

Also, I would use Raw JavaScript to write this small snippet of code because it would be more lightweight for the page to load it.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro @mabasic @cartermp 

It has been a very long journey...

- Nacara has been rewritten 4 times, had issues having the perfect code and interop (getting de-motivated)
- I ported the docs site to Gatbsy enjoyed it and finally saw all the bug and flaws in it...
- Tried to explore others docs site like Huge, Jekyll, etc.
- Settle back to Nacara 😂

And finally, I think I have something ready for review and feedback. Not everything is perfect but at least all the website is now using a single tool Nacara and can be extended.

If you have time to help review this PR it will be greatly appreciated 😇

Because that's quite a big PR, here are the main things to review.

1. The [README.md](https://github.com/fable-compiler/fable-compiler.github.io/pull/98/files) contains a lot of instruction on how things works and how to add new stuff.
2. Test the website to see if everything is working correctly. Like layouts, navigation, mobile view etc.

    Here are the instruction to run a local version of the website:

    1. `npm install`
    2. `npm run watch`
    3. Go to `http://localhost:8080/`

Note: Right now the custom layout of Fable blog index and blog pages, are written in JavaScript because it was easier for me to test things. Also, the code isn't that complex (most of the lines are 1-2 characters to make it easy to read).

I hope to release next week Nacara documentation for both F# and JavaScript usage to make it easier for people to contribute/fix stuff if needed. But if you have a bug or need helps understanding something don't hesitate I will be happy to answer.

I hope, you like the new design of the Website and that we will be able to keep improving it and it's content.

**Comment by MangelMaxime** [comment]
I forgot to say that the last thing I need to add is a CI to check if all the links in the `resources.md` are valid.

I need to check how to do that with Github actions

**Comment by cartermp** [comment]
I shall look this over!

**Comment by cartermp** [comment]
What I see looks good from the code's standpoint, but the gitpod build is broken so there's no version of the site I can easily build there. Does it work for you?

**Comment by MangelMaxime** [comment]
@cartermp The local build doesn't work on your machine? 

I need to check the Gitpod configuration. Yesterday, I encounter a problem with Gitpod on Nacara repository, I can't install `dotnet tools` and so I want to sleep [Bug report](https://community.gitpod.io/t/cannot-run-dotnet-tool-restore/4388)

In theory, this repository doesn't use any dotnet tool so I should be able to make it works. I will try to check it out this evening.

**Comment by alfonsogarciacaro** [comment]
This is awesome @MangelMaxime! Now, when they say that every developer needs to build their own static site generator at least you can say you did try existing solutions ;)

Everything is working for me locally, I will try to make a review later. Thanks again!

**Comment by MangelMaxime** [comment]
> What I see looks good from the code's standpoint, but the gitpod build is broken so there's no version of the site I can easily build there. Does it work for you?

I think I found the source of the error. Nacara was having a restriction on npm for version `>= 7.13.0` and this repository is installing version 7.12 only. I am not sure what it doesn't install the latest version of npm even when asked for...

I am relaxing the requirements on Nacara side to be `>=7.0.0` as there is no real reason to have require more than that in theory. Will see how it goes

**Comment by MangelMaxime** [comment]
Gitpod should be working now.

**Review by cartermp — APPROVED** [review]
Looks great!

**Review by alfonsogarciacaro — APPROVED** [review]
Thanks again for this hard work @MangelMaxime, this looks great! Hopefully Nacara can also be used now to build websites for other projects 💪 

I think the PR is good to merge, but here are a few comments after reviewing in case they help:

- README looks perfect. I think it's great to have the post data directly in the .md file instead of having to edit blog.fs, this should make it easier to add new posts. If something, maybe adding a sentence about editing documentation (though the Edit button in each page should be also quite obvious).
- The Gitter and Youtube icons seem to be missing from the title bar
- It's great to have a consistent style throughout the website. The only thing is the landing page (and maybe also the blog index) looks a bit too white, would it be possible to have a slightly grey background as it's now?
- I would remove the mentions to Awesome list at the top and bottom of the Resources section. Later I will try to make a deeper review and merge some items from the community.json if needed.

**Comment by MangelMaxime** [comment]
> Hopefully Nacara can also be used now to build websites for other projects muscle

That's the idea ;)

>     * README looks perfect. I think it's great to have the post data directly in the .md file instead of having to edit blog.fs, this should make it easier to add new posts. If something, maybe adding a sentence about editing documentation (though the Edit button in each page should be also quite obvious).

I focused mostly on non trivial task and that's why I added the `Architecture` to explains what is in each folders.

If you have an idea how to word it we can of course add a note.

>     * The Gitter and Youtube icons seem to be missing from the title bar

I don't know where those icons/elements should be? Can you please show me with a screenshot?

In theory, only the Github and Twitter elements of the navbar have an icon.

image

On the right end of the navbar.

>     * It's great to have a consistent style throughout the website. The only thing is the landing page (and maybe also the blog index) looks a bit too white, would it be possible to have a slightly grey background as it's now?

The slightly grey background doesn't play well with the code snippet border etc. I tried to make it work and it doesn't...

I had the same feeling as you at first but in the end it help have a modern/clean look to the website.

For me the landing page looks good but the blog page index could needs some layout redesign. I think having a 2 columns layout with each column sligthy offset vertically would looks nicer and helps show more blog items "quickly".

I was kind of stuck on the layout for several days but perhaps I have an idea on how to archive that. I will try to it and see how it goes.

> I would remove the mentions to Awesome list at the top and bottom of the Resources section. Later I will try to make a deeper review and merge some items from the community.json if needed.

I wasn't sure if we wanted to remove it or not. It has been removed.

**Comment by alfonsogarciacaro** [comment]
Thanks for the answers @MangelMaxime. Ok, then let's keep the background as is. I've added the Gitter and Youtube icons from the [current configuration](https://github.com/fable-compiler/fable-compiler.github.io/blob/586646cc3ac95880353b80d4ec9bc1b23a4d395b/src/components/Navbar.fs#L40-L64). Let's merge this! 🚀

**Pull request merged**
