### PR TITLE
Adding Blue Trading to companies using Fable

### PR DESCRIPTION
**Pull request by ericharding**
We built an administration UI for our server back end using Fable and it's officially in production as of last Monday.  Our experience with Fable has been amazing so far.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Awesome, thank you! Very happy to hear that Fable is useful to you :)

**Comment by ericharding** [comment]
I just noticed I have a typo. The image is svg not png.  I need to amend the pr.

**Comment by ericharding** [comment]
I guess I have to make another pr

**Comment by alfonsogarciacaro** [comment]
No worries, I just fixed it. It should be online now :)

**Comment by ericharding** [comment]
Thanks!

**Pull request merged**
