### PR TITLE
watch mode  `#if DEBUG` compiler directives.

### PR DESCRIPTION
**Pull request by goswinr**
I think this is worth mentioning. Please reword if not clear.

### CODE REVIEW

**Comment by goswinr** [comment]
I was confused that the DEBUG code was running,  because I used a nuget package that was build in Release mode. But of course Fable still sees the DEBUG symbol in the source included in the nuget. And uses them during watching.

**Comment by goswinr** [comment]
I am not sure what to do about the failing 429 medium links in the build check ?

**Comment by MangelMaxime** [comment]
> I am not sure what to do about the failing 429 medium links in the build check ?

I think `awesome_bot` has a `--white-list` options which would allows us to avoid error on this URLs caused by Medium firewall probably (?).

---------

Regarding the `DEBUG` directives, I feel like this is not the right place to put it. Perhaps, we could have a dedicated CLI page like [Vitest does](https://vitest.dev/guide/cli.html) ?

We could perhaps have a `CLI` or `Fable CLI` page under `Getting started` or `Introduction`?

If we decide to keep it under the `build-and-run` page we also need to update the `build-and-run` page of others languages for parity.

**Comment by MangelMaxime** [comment]
Thank you for the PR.

I ended up creating a dedicated page. It will probably be reworked in the future as I plan to rework Fable CLI because I find it confusing and not using the best CLI practices.

I cherry picked the commit you made regarding 404 and url verification.

**Pull request closed without merging**
