### PR TITLE
update gitpod and build definitions

### PR DESCRIPTION
**Pull request by cartermp**
Draft until I verify the cloud environment works as expected

### CODE REVIEW

**Comment by cartermp** [comment]
Okay, seems load build/load in the environment just fine!

**Comment by cartermp** [comment]
....running the npm script wiped out 5k lines of the lock file :D

**Comment by MangelMaxime** [comment]
> ....running the npm script wiped out 5k lines of the lock file :D

That's because you are using not using the latest version of npm. 

Starting from npm 7, they added a new format to the `package-lock.json`.

So you removed the v2 format from the file

image

**Comment by MangelMaxime** [comment]
Instead of removing the docker file, we could change the docker image to something like that:

```docker
FROM gitpod/workspace-dotnet:latest

USER gitpod

RUN bash -c ". .nvm/nvm.sh \
             && nvm install v14 && nvm alias default v14 \
             && npm i -g npm@7 " \
```

Like that we use the default dotnet image because I had a hard time making dotnet work correctly on gitpod. And just configure nvm/npm to the "right" versions

**Comment by MangelMaxime** [comment]
Ok, I made so test and this dockerfile does what I want:

```
FROM gitpod/workspace-dotnet:latest

USER gitpod

# Install & use custom Node.js version
ENV NODE_VERSION=14
RUN bash -c ". .nvm/nvm.sh && \
        nvm install ${NODE_VERSION} && \
        nvm alias default ${NODE_VERSION}"

RUN npm i -g npm@7
```

It installs the specified version of node.js and install the latest version of npm@7.X.X

```
gitpod /workspace/Fable.Form $ which node
/home/gitpod/.nvm/versions/node/v14.16.1/bin/node
gitpod /workspace/Fable.Form $ npm --version
7.12.1
gitpod /workspace/Fable.Form $ 
```

In order to avoid people using an incorrect version of `npm` or `node` we can add these lines to the package.json file:

```json
"engines": {
    "node": ">=14.0.0",
    "npm": ">=7.0.0"
  }
```

We also need to add a `.npmrc` file with `engine-strict=true` in it. This will make `npm` failed if the engines are incorrect otherwise, the user will only get a warning.

For npm, I know we want `>= 7.0.0` to avoid having the `package-lock.json` files being striped of the v2 format.
As for the node version we need to decide if we want to use the latest lts or make the required lower.

**Comment by cartermp** [comment]
> Like that we use the default dotnet image because I had a hard time making dotnet work correctly on gitpod.

Yeah, I actually contributed to their images a while back so that it always has the latest .NET SDK or the latest LTS via the `dotnet-install` script. Now it's quite a stable system.

**Comment by cartermp** [comment]
Alright, this is ready @MangelMaxime

**Comment by MangelMaxime** [comment]
> 
> 
> > Like that we use the default dotnet image because I had a hard time making dotnet work correctly on gitpod.
> 
> Yeah, I actually contributed to their images a while back so that it always has the latest .NET SDK or the latest LTS via the `dotnet-install` script. Now it's quite a stable system.

Thank you very much for that 🙏 I remember having the same configuration not having the same output at the time it was really frustrating.

**Pull request merged**
